services:
  backend:
    image: ghcr.io/jeffbuyunhe/personal-website-backend:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env

  frontend:
    image: ghcr.io/jeffbuyunhe/personal-website-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
