name: Deploy 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - run: echo "${{ secrets.ENV_FRONTEND }}" > ./frontend/.env
      - run: echo "${{ secrets.ENV_BACKEND }}" > ./backend/.env

      - run: npm ci
      - run: npm run install-all
      - run: npm run build
      
      - name: rsync update
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/app/
          remote_host: "${{ secrets.SSH_HOST }}"
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: ubuntu
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: cd ~/scripts/ && ./restart-frontend.sh && ./restart-backend.sh